name: MiniTorch tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        python -m pip install flake8 pep8-naming
        python -m pip install -r requirements.txt
        python -m pip install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 --ignore "N801, E203, E266, E501, W503, F812, F401, F841, E741, N803, N802, N806" minitorch/ tests/
    - name: Test Modules 0 and 1
      run: |
        python -m pytest tests -x -m task0_1
        python -m pytest tests -x -m task0_2
        python -m pytest tests -x -m task0_3
        python -m pytest tests -x -m task0_4

        python -m pytest tests -x -m task1_1
        python -m pytest tests -x -m task1_2
        python -m pytest tests -x -m task1_3
        python -m pytest tests -x -m task1_4

        # Добавлю как сделаю
        # python -m pytest tests -x -m task2_1
        # python -m pytest tests -x -m task2_2
        # python -m pytest tests -x -m task2_3
        # python -m pytest tests -x -m task2_4
        # python -m pytest tests -x -m task3_1
        # python -m pytest tests -x -m task3_2
        # python -m pytest tests -x -m task3_3
        # python -m pytest tests -x -m task3_4
        # python -m pytest tests -x -m task4_1
        # python -m pytest tests -x -m task4_2
        # python -m pytest tests -x -m task4_3
        # python -m pytest tests -x -m task4_4
